spring:
  application:
    name: @name@
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  security:
    user:
      name: root
      password: 123

person:
  name: chen
  age: 18

test:
  duration: PT1H30S

logging:
  file: my.log
